"""
This type stub file was generated by pyright.
"""

from pycsp3.solvers.solver import SolverProcess

ACE_DIR = ...
ACE_CP = ...
class Ace(SolverProcess):
    def __init__(self) -> None:
        ...
    
    def switch_to_extraction(self): # -> None:
        ...
    
    def parse_general_options(self, string_options, dict_options, dict_simplified_options):
        ...
    


