"""
This type stub file was generated by pyright.
"""

"""
@created: 20.07.20
@author: felix
"""
logger = ...
ORIGINAL_DUCK_TYPES = ...
def remove_subclass(args, subclass):
    ...

SEVERITY_CONFIG = ...
exclude_builtins = ...
def install_st_m(): # -> None:
    ...

def action(f, frefs, type_function): # -> property:
    """
    This code is original from Ruud van der Ham https://github.com/salabim/easy_property
    """
    ...

