"""
This type stub file was generated by pyright.
"""

from typing import Any, Union

"""
@created: 07.06.20
@author: felix
"""
class CachedSet(set):
    """
    Warning only use for caching when Memory limit is reached all items will be cleared
    """
    def __init__(self, memory_limit: Union[int, float] = ..., *args, **kwargs) -> None:
        """
        :param memory_limit: in MB
        """
        ...
    
    def add(self, element: Any) -> None:
        ...
    


