"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""
@created: 20.07.20
@author: felix
"""
class SEVERITY_LEVEL(Enum):
    DISABLED = ...
    ENABLED = ...
    WARNING = ...
    @property
    def value_as_str(self): # -> str:
        ...
    


def set_severity_level(_level: SEVERITY_LEVEL): # -> None:
    ...

