"""
This type stub file was generated by pyright.
"""

from typing import Any, _GenericAlias, _SpecialForm

"""
@created: 30.05.21
@author: felix
"""
class _Validator(_GenericAlias, _root=True):
    _name = ...
    def __getitem__(self, item):
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class _IterValidator(_GenericAlias, _root=True):
    _name = ...
    def __getitem__(self, item):
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


@_SpecialForm
def Validator(self, parameters, *args, **kwargs): # -> _Validator:
    ...

@_SpecialForm
def IterValidator(self, parameters, *args, **kwargs): # -> _IterValidator:
    ...

class FrozenType:
    __slots__ = ...
    def __init__(self, required_type, stored_value=...) -> None:
        ...
    
    def __get__(self, instance=..., owner=...): # -> None:
        ...
    
    def __set__(self, instance=..., value=...): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __doc__(self):
        ...
    
    @classmethod
    def cast(cls, instance, origin, new): # -> tuple[FrozenType, Any, Any]:
        """
        change the type explicit not implicit by accident
        """
        ...
    
    def error_msg(self, value: Any, attribute_name: str = ...) -> Exception:
        ...
    


