"""
This type stub file was generated by pyright.
"""

def warning(message): # -> None:
    ...

class _Options:
    def __init__(self) -> None:
        ...
    
    def set_values(self, *values): # -> None:
        ...
    
    def set_flags(self, *flags): # -> None:
        ...
    
    def get(self, name): # -> Any:
        ...
    
    def consume_parameter(self): # -> None:
        ...
    
    def parse(self, args): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


options = ...
