"""
This type stub file was generated by pyright.
"""

def process_options(solving): # -> tuple[Any, dict[Any, Any] | Any | dict[Any, Any | None] | None, dict[Any, Any] | Any | dict[Any, Any | None] | None]:
    ...

class Logger:
    def __init__(self, prefix_end=..., verbose=..., path=...) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def read(self): # -> str:
        ...
    
    def close(self): # -> None:
        ...
    


class Instantiation:
    def __init__(self, root, variables, values, pretty_solution) -> None:
        ...
    
    def __repr__(self): # -> tuple[Any, Any]:
        ...
    
    def __str__(self) -> str:
        ...
    


class SolverProcess:
    automatic_call = ...
    def __init__(self, *, name, command, cp) -> None:
        ...
    
    def command(self, _command): # -> None:
        ...
    
    def get_logger(self): # -> None:
        ...
    
    def setting(self, value): # -> None:
        ...
    
    def log_suffix(self, _extend_filename_logger): # -> None:
        ...
    
    def parse_general_options(self, string_options, dict_options, dict_simplified_options):
        ...
    
    def solve(self, instance, string_options=..., dict_options=..., dict_simplified_options=..., compiler=..., *, verbose=..., automatic=..., extraction=...): # -> Literal[TypeStatus.UNKNOWN, TypeStatus.CORE, TypeStatus.UNSAT, TypeStatus.OPTIMUM, TypeStatus.SAT] | None:
        ...
    
    def switch_to_extraction(self): # -> None:
        ...
    


