"""
This type stub file was generated by pyright.
"""

from pycsp3.solvers.solver import SolverProcess

CHOCO_DIR = ...
CHOCO_CP = ...
class Choco(SolverProcess):
    def __init__(self) -> None:
        ...
    
    def parse_general_options(self, string_options, dict_options, dict_simplified_options):
        ...
    


