"""
This type stub file was generated by pyright.
"""

from pycsp3.classes.main.constraints import ConstraintUnmergeable

class Objective(ConstraintUnmergeable):
    def __init__(self, way) -> None:
        ...
    


class ObjectiveExpression(Objective):
    def __init__(self, way, expression) -> None:
        ...
    


class ObjectivePartial(Objective):
    def __init__(self, way, partial) -> None:
        ...
    


