"""
This type stub file was generated by pyright.
"""

class Domain:
    def __init__(self, *args) -> None:
        ...
    
    def __iter__(self): # -> Iterator[float]:
        ...
    
    def __getitem__(self, item):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def smallest_value(self): # -> float | int:
        ...
    
    def greatest_value(self): # -> float | int:
        ...
    
    def all_values(self): # -> list[float]:
        ...
    
    def is_binary(self): # -> bool:
        ...
    


class Variable:
    name2obj = ...
    arrays = ...
    @staticmethod
    def build_names_array(name, sizes, mins, indexes=...): # -> list[Any]:
        ...
    
    @staticmethod
    def build_domain(name, domain, indexes): # -> Domain | None:
        ...
    
    @staticmethod
    def build_variable(name, domain, indexes): # -> VariableInteger | VariableSymbolic | None:
        ...
    
    @staticmethod
    def build_variables_array(name, sizes, domain, indexes=...): # -> list[VariableInteger | VariableSymbolic | None] | list[Any] | VariableInteger | VariableSymbolic | None:
        ...
    
    def __init__(self, name, dom, *, inverse=..., negation=...) -> None:
        ...
    
    def name(self, name): # -> None:
        ...
    
    def eq__safe(self, other): # -> Literal[False]:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __invert__(self): # -> Variable:
        ...
    
    def __neg__(self): # -> Variable:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self): # -> Any:
        ...
    


class VariableInteger(Variable):
    def __init__(self, name, dom) -> None:
        ...
    
    def among(self, *values): # -> ConstraintDummyConstant | Node:
        ...
    
    def not_among(self, *values): # -> ConstraintDummyConstant | Node:
        ...
    


class VariableSymbolic(Variable):
    def __init__(self, name, dom) -> None:
        ...
    


