"""
This type stub file was generated by pyright.
"""

class SequenceOfSuccessiveVariables:
    def __init__(self, x) -> None:
        ...
    
    def differ_just_at(self, t): # -> int:
        ...
    
    def can_be_extended_with(self, id): # -> bool | None:
        ...
    
    def __repr__(self):
        ...
    


def build_partition(variables, preserve_order): # -> tuple[None, None] | tuple[list[list[Any]], str] | tuple[list[Any], str]:
    ...

def compact(variables, *, preserve_order=..., group_args=...): # -> list[Any] | str:
    ...

def build_compact_forms(): # -> None:
    ...

