"""
This type stub file was generated by pyright.
"""

def handle_slides(): # -> None:
    ...

def detect_slides_recursively(ctr_entities): # -> None:
    ...

def canonize_blocks_of_slides(ctr_entities, parent=...): # -> None:
    ...

