"""
This type stub file was generated by pyright.
"""

from collections import OrderedDict

SIZE_LIMIT_FOR_USING_AS = ...
class DefaultListOrderedDict(OrderedDict):
    def __missing__(self, k):
        ...
    


def build_document(): # -> None:
    ...

