"""
This type stub file was generated by pyright.
"""

def to_ordinary_table(table, domains, *, possibly_starred=...): # -> list[Any]:
    """
    Converts the specified table that may contain hybrid restrictions and stars into an ordinary table (or a starred table).
    The table contains r-tuples and the domain to be considered are any index i of the tuples is given by domains[i].
    In case, domains[i] is an integer, it is automatically transformed into a range.

    :param table: a table (possibly hybrid or starred)
    :param domains: the domains of integers to be considered for each column of the table
    :param possibly_starred: if True, the returned table may be starred (and not purely ordinary)
    :return: an ordinary or starred table
    """
    ...

def to_reified_ordinary_table(table, domains): # -> list[Any]:
    ...

def to_starred_table_for_no_overlap1(x1, x2, w1, w2): # -> list[Any]:
    ...

def to_starred_table_for_no_overlap2(x1, x2, y1, y2, w1, w2, h1, h2): # -> list[Any]:
    ...

